name: Автогенерация постов для FuturePulse

on:
  schedule:
    - cron: "0 6,18 * * *" # 2 раза в день в 06:00 и 18:00 по UTC
  workflow_dispatch: # позволяет запуск вручную из интерфейса GitHub

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Клонировать репозиторий
        uses: actions/checkout@v3

      - name: Установить Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Установить зависимости
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Запустить генерацию постов
        env:
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_DRAFT_CHANNEL_ID: ${{ secrets.TELEGRAM_DRAFT_CHANNEL_ID }}
        run: |
          python generate_from_rss.py
          python generate_and_post.py
