name: Автогенерация постов для FuturePulse

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8,20 * * *" # 11:00 и 23:00 по МСК

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Клонировать репозиторий
        uses: actions/checkout@v3

      - name: Установить Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Установить зависимости
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Запустить генерацию и публикацию постов
        env:
          TOGETHER_API_KEY: ${{ secrets.TOGETHER_API_KEY }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          DRAFT_CHAT_ID: ${{ secrets.DRAFT_CHAT_ID }}
        run: |
          python generate_from_rss.py
          python generate_and_post.py
