name: Автогенерация постов для FuturePulse

on:
  workflow_dispatch: # ручной запуск с GitHub
  schedule:
    - cron: "0 8,20 * * *" # каждый день в 08:00 и 20:00 по UTC (11:00 и 23:00 МСК)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Клонировать репозиторий
        uses: actions/checkout@v3

      - name: Установить Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Установить зависимости
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Проверка ключа OPENROUTER_API_KEY
        run: echo "OPENROUTER_API_KEY is ${{ secrets.OPENROUTER_API_KEY }}"

      - name: Запустить генерацию постов
        env:
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_DRAFT_CHANNEL_ID: ${{ secrets.TELEGRAM_DRAFT_CHANNEL_ID }}
        run: |
          python generate_from_rss.py
          python generate_and_post.py
