name: Автогенерация постов для FuturePulse

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Клонировать репозиторий
        uses: actions/checkout@v3

      - name: Установить Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Установить зависимости
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Запустить генерацию и публикацию постов
        env:
          TOGETHER_API_KEY: ${{ secrets.TOGETHER_API_KEY }}
          BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          DRAFT_CHAT_ID: ${{ secrets.TELEGRAM_DRAFT_CHANNEL_ID }}
        run: |
          python generate_from_rss.py
          python generate_and_post.py

      - name: Сохранить сгенерированные посты и логи
        uses: actions/upload-artifact@v3
        with:
          name: generated-posts-and-logs
          path: |
            posts/
            logs/
